#!/bin/zsh
set -euo pipefail

script_dir="${0:A:h}"
package_dir="${script_dir:h}"
output_dir="${1:-${package_dir}/Release}"
app_dir="${output_dir}/PinChat.app"
baseline="${output_dir}/REQUIREMENTS_BASELINE_v1.0.md"
baseline_checksum="${output_dir}/REQUIREMENTS_BASELINE_v1.0.sha256"
optimization_baseline="${output_dir}/OPTIMIZATION_REQUIREMENTS_BASELINE_v1.1.md"
optimization_baseline_checksum="${output_dir}/OPTIMIZATION_REQUIREMENTS_BASELINE_v1.1.sha256"
product_baseline="${output_dir}/PRODUCT_REQUIREMENTS_BASELINE_v2.0.md"
product_baseline_checksum="${output_dir}/PRODUCT_REQUIREMENTS_BASELINE_v2.0.sha256"
visual_baseline="${output_dir}/VISUAL_OPTIMIZATION_REQUIREMENTS_BASELINE_v2.1.md"
visual_baseline_checksum="${output_dir}/VISUAL_OPTIMIZATION_REQUIREMENTS_BASELINE_v2.1.sha256"
activity_baseline="${output_dir}/DESKTOP_ACTIVITY_REQUIREMENTS_BASELINE_v2.2.md"
activity_baseline_checksum="${output_dir}/DESKTOP_ACTIVITY_REQUIREMENTS_BASELINE_v2.2.sha256"
handoff_baseline="${output_dir}/HANDOFF_FIX_REQUIREMENTS_BASELINE_v2.3.md"
handoff_baseline_checksum="${output_dir}/HANDOFF_FIX_REQUIREMENTS_BASELINE_v2.3.sha256"
attachment_baseline="${output_dir}/ATTACHMENT_AND_SURFACE_REQUIREMENTS_BASELINE_v2.4.md"
attachment_baseline_checksum="${output_dir}/ATTACHMENT_AND_SURFACE_REQUIREMENTS_BASELINE_v2.4.sha256"
multitask_baseline="${output_dir}/MULTITASK_AND_CAPABILITIES_REQUIREMENTS_BASELINE_v2.5.md"
multitask_baseline_checksum="${output_dir}/MULTITASK_AND_CAPABILITIES_REQUIREMENTS_BASELINE_v2.5.sha256"
presentation_baseline="${output_dir}/INTELLIGENT_PRESENTATION_REQUIREMENTS_BASELINE_v3.0.md"
presentation_baseline_checksum="${output_dir}/INTELLIGENT_PRESENTATION_REQUIREMENTS_BASELINE_v3.0.sha256"
pet_interaction_baseline="${output_dir}/PET_INTERACTION_REQUIREMENTS_BASELINE_v3.1.md"
pet_interaction_baseline_checksum="${output_dir}/PET_INTERACTION_REQUIREMENTS_BASELINE_v3.1.sha256"
permissions_baseline="${output_dir}/PERMISSIONS_REQUIREMENTS_BASELINE_v3.2.md"
permissions_baseline_checksum="${output_dir}/PERMISSIONS_REQUIREMENTS_BASELINE_v3.2.sha256"
permission_follow_baseline="${output_dir}/CODEX_PERMISSION_FOLLOW_REQUIREMENTS_BASELINE_v3.3.md"
permission_follow_baseline_checksum="${output_dir}/CODEX_PERMISSION_FOLLOW_REQUIREMENTS_BASELINE_v3.3.sha256"
native_input_baseline="${output_dir}/NATIVE_INPUT_AND_DROP_REQUIREMENTS_BASELINE_v3.4.md"
native_input_baseline_checksum="${output_dir}/NATIVE_INPUT_AND_DROP_REQUIREMENTS_BASELINE_v3.4.sha256"
screenshot_drop_baseline="${output_dir}/SCREENSHOT_DROP_FIX_REQUIREMENTS_BASELINE_v3.5.md"
screenshot_drop_baseline_checksum="${output_dir}/SCREENSHOT_DROP_FIX_REQUIREMENTS_BASELINE_v3.5.sha256"

cd "$package_dir"
swift test
"$script_dir/build-app.sh" "$output_dir"

test -x "$app_dir/Contents/MacOS/PinChat"
plutil -lint "$app_dir/Contents/Info.plist"
test "$(/usr/libexec/PlistBuddy -c 'Print :LSUIElement' "$app_dir/Contents/Info.plist")" = "true"
test "$(/usr/libexec/PlistBuddy -c 'Print :LSMinimumSystemVersion' "$app_dir/Contents/Info.plist")" = "14.0"
codesign --verify --deep --strict "$app_dir"

test -r "$baseline"
test -r "$baseline_checksum"
test -r "$optimization_baseline"
test -r "$optimization_baseline_checksum"
test -r "$product_baseline"
test -r "$product_baseline_checksum"
test -r "$visual_baseline"
test -r "$visual_baseline_checksum"
test -r "$activity_baseline"
test -r "$activity_baseline_checksum"
test -r "$handoff_baseline"
test -r "$handoff_baseline_checksum"
test -r "$attachment_baseline"
test -r "$attachment_baseline_checksum"
test -r "$multitask_baseline"
test -r "$multitask_baseline_checksum"
test -r "$presentation_baseline"
test -r "$presentation_baseline_checksum"
test -r "$pet_interaction_baseline"
test -r "$pet_interaction_baseline_checksum"
test -r "$permissions_baseline"
test -r "$permissions_baseline_checksum"
test -r "$permission_follow_baseline"
test -r "$permission_follow_baseline_checksum"
test -r "$native_input_baseline"
test -r "$native_input_baseline_checksum"
test -r "$screenshot_drop_baseline"
test -r "$screenshot_drop_baseline_checksum"
(
    cd "$output_dir"
    shasum -a 256 -c "${baseline_checksum:t}"
    shasum -a 256 -c "${optimization_baseline_checksum:t}"
    shasum -a 256 -c "${product_baseline_checksum:t}"
    shasum -a 256 -c "${visual_baseline_checksum:t}"
    shasum -a 256 -c "${activity_baseline_checksum:t}"
    shasum -a 256 -c "${handoff_baseline_checksum:t}"
    shasum -a 256 -c "${attachment_baseline_checksum:t}"
    shasum -a 256 -c "${multitask_baseline_checksum:t}"
    shasum -a 256 -c "${presentation_baseline_checksum:t}"
    shasum -a 256 -c "${pet_interaction_baseline_checksum:t}"
    shasum -a 256 -c "${permissions_baseline_checksum:t}"
    shasum -a 256 -c "${permission_follow_baseline_checksum:t}"
    shasum -a 256 -c "${native_input_baseline_checksum:t}"
    shasum -a 256 -c "${screenshot_drop_baseline_checksum:t}"
)

echo "PinChat release verification passed: $app_dir"
